### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#1207]
### Todos

- [x] SonataMediaBundle - error (is_callable changed behavior)
- [x] SonataBlockBundle - error (problem with this line: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/AbstractBlockService.php#L60)
- [x] SonataPageBundle - error (orm does not work yet)
- [x] SonataIntlBundle - error
- [x] SonataFormatterBundle - prophecy
- [x] exporter - mongodb
- [x] ecommerce - error
- [x] SonataMongodbAdminBundle - mongodb
- [x] doctrine-extensions - mongodb

this is the reason for failing builds: error is for some error related to a incompatibility with php7-8
the mongodb ones cannot be fixed until we get a version for mongodb compatible with php 8
the rest can be fixed
Formatter and Media are the hardest one, a lot of rewrite needed to remove prophecy

### After Todos are done

* [x] revert https://github.com/sonata-project/dev-kit/pull/1202 ❗

**Comment by jordisala1991** [comment]
The only ones that are missing now (we need to merge the one in exporter and the one in mediabundle) are:

- ecommerce (there is a weird behavior in bc functions)
- SonataBlockBundle

The blocking one IMO is the block bundle, because once that is fixed, we can add php 8.0 in composer.json and we can start adding it on dev-kit for all repos (except ecommerce)

**Comment by jordisala1991** [comment]
This one is the last one to fix: https://github.com/sonata-project/ecommerce/pull/743

@OskarStark after this one, can you revert #1202  ?

After that we can start adding php 8 as required build, and then (once all dependencies are compatible, start adding 8.0 on our composer.json)

**Comment by VincentLanglet** [comment]
What's next @jordisala1991 ?

**Comment by jordisala1991** [comment]
For me this one is done already, the only missing part is because of some dependencies like the entity audit things, and thatd already on other issues
