### ISSUE TITLE
Support for PHP 8.0

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#1433]
Getting from sandbox(composer why-not php 8.0):
```
sonata-project/sandbox                dev-master   requires  php (^7.4)            
doctrine/orm                          9999999-dev  requires  php (^7.1)            
doctrine/reflection                   1.3.x-dev    requires  php (^7.1)            
friendsofsymfony/comment-bundle       2.x-dev      requires  php (^5.5.9|~7.0)     
friendsofsymfony/user-bundle          2.x-dev      requires  php (^5.5.9 || ^7.0)  
knplabs/knp-markdown-bundle           1.8.1        requires  php (^7.1.3)          
kriswallsmith/buzz                    v0.16.0      requires  php (^5.4 || ^7.0)    
sonata-project/cache                  1.x-dev      requires  php (^7.1)            
sonata-project/cache-bundle           2.x-dev      requires  php (^5.6 || ^7.0)    
sonata-project/classification-bundle  3.13.2       requires  php (^7.2)            
sonata-project/comment-bundle         9999999-dev  requires  php (^7.3)            
sonata-project/easy-extends-bundle    9999999-dev  requires  php (^7.1)            
sonata-project/ecommerce              9999999-dev  requires  php (^7.3)            
sonata-project/formatter-bundle       9999999-dev  requires  php (^7.3)            
sonata-project/media-bundle           3.30.0       requires  php (^7.3)            
sonata-project/news-bundle            9999999-dev  requires  php (^7.3)            
sonata-project/notification-bundle    3.11.0       requires  php (^7.3)            
sonata-project/page-bundle            9999999-dev  requires  php (^7.2)            
sonata-project/timeline-bundle        9999999-dev  requires  php (^7.3)            
sonata-project/user-bundle            9999999-dev  requires  php (^7.3)            
stephpy/timeline-bundle               3.1.1        requires  php (^7.1)     
```
### TODO:

- [x] sonata-project/cache
- [x] sonata-project/cache-bundle
- [x] sonata-project/classification-bundle 
- [ ] sonata-project/comment-bundle 
- [ ] sonata-project/ecommerce
- [x] sonata-project/formatter-bundle
- [x] sonata-project/media-bundle
- [ ] sonata-project/news-bundle
- [x] sonata-project/page-bundle
- [ ] sonata-project/timeline-bundle
- [x] sonata-project/user-bundle

**Comment by wbloszyk** [comment]
> Cache 2.0 does support php 8
> Same for cacheBundle 3.x (needs a release)

Feel free to update checklist.

**Comment by jordisala1991** [comment]
I think this issue is complete. The missing bundles are abandoned.
