### ISSUE TITLE
DEPRECATE REST APIs

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#1465]
Now we have a lot of problems with keeps APIs like:
- can not add support for symfony/config 5.x becouse nelmio/api-doc-bundle 2.x have config bug
- can not use nelmio/api-doc-bundle 4.x becouse it is in conflict
- nelmio/api-doc-bundle 2.x have not support symfony 5
- not all sonata bundles support nelmio 3.x 

My solution is move APIs to seperate bundle or bundles. This will move all dependencies require to REST API to seperate bundle and allow us ignire it in 4.0 milestones.

For example:
- SonataMediaBundle will provide abstractMediaApiController
- In API bundle it will be extended with annotation for specify nelmio version
- 1.x - nelmio 2
- 2.x nelmio 3
- 3.x nelmio 4
- 4.x api platform 
- or we can use only one version

IMO we should do it in one bundle `sonata-project/api-bundle`.

WDYT? @sonata-project/contributors 

# TODO:
Deprecate REST API in stable branch:
- [x] [SonataClassificationBundle](https://github.com/sonata-project/SonataClassificationBundle/pull/735)
- [x] [SonataMediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/2118)
- [x] [SonataNewsBundle](https://github.com/sonata-project/SonataNewsBundle/pull/773)
- [x] [SonataPageBundle](https://github.com/sonata-project/SonataPageBundle/pull/1365)
- [x] SonataUserBundle

Remove REST API in unstable branch:
- [x] SonataClassificationBundle
- [x] [SonataMediaBundle](https://github.com/sonata-project/SonataMediaBundle/pull/2122)
- [x] [SonataNewsBundle](https://github.com/sonata-project/SonataNewsBundle/pull/780)
- [x] SonataPageBundle
- [x] SonataUserBundle

Bundles that we will not be deprecating the api (abandoned)
- ecomerce
- SonataNotificationBundle

**Comment by core23** [comment]
Which APIs do you mean? REST?

**Comment by core23** [comment]
> My solution is move APIs to seperate bundle or bundles. This will move all dependencies require to REST API to seperate bundle and allow us ignire it in 4.0 milestones.

:+1: 

> IMO we should do it in one bundle `sonata-project/api-bundle`.

:-1: This will bring other problems. If you just require `api-bundle`, it would install ALL bundles with an api or you will get some strange `require-dev` / `conflict` entries.

Might relate to this issue: https://github.com/sonata-project/dev-kit/issues/537

**Comment by wbloszyk** [comment]
> > IMO we should do it in one bundle `sonata-project/api-bundle`.
> 
> 👎 This will bring other problems. If you just require `api-bundle`, it would install ALL bundles with an api or you will get some strange `require-dev` / `conflict` entries.

api-bundle will be in sugesstion section for each bundle where it is possible to use with conflict to set minimum api-bundle version.
in api-bundle we should add only conflict with minimum version. Require-dev can be ingore. Test can be provide by GitHub actions.

> Might relate to this issue: #537

Simmilar but here dependencies are diffrence third part bundles. in admin dependencies are one ower bundle.

**Comment by VincentLanglet** [comment]
With @jordisala1991, we're currently discussing a lot about the Media bundle which has Rest API, and the issue with the duplicate code in datagridBundle and adminBundle.

In the media bundle
- If you don't use the rest API, you don't need the datagrid bundle. (Since https://github.com/sonata-project/SonataMediaBundle/pull/2041)
- If you only use the rest API, you don't need the admin-bundle.

If we split this, we have to
- Remove the usage of the PageableInterface in the original MediaBundle https://github.com/sonata-project/SonataMediaBundle/blob/master/src/Model/MediaManagerInterface.php#L23 (because it's used only for API)
- Remove the method `getPager` in the implementation
- Remove the datagridBundle dependency
- Decorate the MediaManager in the new MediaApiBundle to implements PageableInterface

It requires some work but would be a nice way to stop using datagridBundle in our admin-related bundles.

**Comment by VincentLanglet** [comment]
The new strategy is to deprecate the REST API https://github.com/sonata-project/SonataMediaBundle/commit/e985c2c40cdb5c60639fc7e014229bf8dff943c7

**Comment by wbloszyk** [comment]
Updated.

**Comment by jordisala1991** [comment]
I remove ecommerce an NewsBundle, since they are abandoned and will not get major releases.

**Comment by VincentLanglet** [comment]
Deprecating/Removing the REST Api will allow to remove the datagrid-bundle dependency for the next majors.
We will be able to abandon it then as proposed in https://github.com/sonata-project/dev-kit/issues/1669

**Comment by VincentLanglet** [comment]
SonataNotification and SonataUser is not yet abandoned, so we should still deprecate the rest API

**Comment by wbloszyk** [comment]
> SonataNotification and SonataUser is not yet abandoned, so we should still deprecate the rest API

We font wanna release these bundles in Sonata 4, so it is no reason to deprecate ReST API for them. They will be deprecated as whole bundle.

**Comment by VincentLanglet** [comment]
> > SonataNotification and SonataUser is not yet abandoned, so we should still deprecate the rest API
> 
> We dont wanna release these bundles in Sonata 4, so it is no reason to deprecate ReST API for them. They will be deprecated as whole bundle.

SonataNotification is not related to SonataAdmin, and a major could be created if needed if it helps people to migrate, dunno.
And the futur of SonataUser is not clear. So I cannot say there won't be any major first.
SonataNews was abandoned, and yet, there is still some PR on it.

Maybe they will be deprecated/abandoned, but currently there are not.

**Comment by VincentLanglet** [comment]
As far, UserBundle and Notification are not abandoned so we should still deprecate the rest API.
This will allow us to deprecate the DatagridBundle.

**Comment by VincentLanglet** [comment]
And as mention in https://github.com/sonata-project/dev-kit/issues/1714#issuecomment-939312702

We should deprecate the API-Rest, all the method getPager and all the PageableManager extension.

**Comment by jordisala1991** [comment]
Do you think it is needed to deprecate NotificationBundle API? It will be deprecated when pagerbundle drops its usage (and it is required for next major)

**Comment by VincentLanglet** [comment]
Let's close it then.

**Comment by VincentLanglet** [comment]
There is https://github.com/sonata-project/SonataPageBundle/issues/1238 to remove NotificationBundle from PageBundle
