### ISSUE TITLE
Road to Sonata 4

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#216]
Here's a meta issue to rule them all. If you can edit, don't hesitate to add items.

- [ ] release dependencies (libraries that are required by other sonata libraries). These libraries need to switch to a 3 branch system because of the transition period. ~~ We can revert to a 2 branch system after all dependent bundles have a new major release~~ (won't necessarily be a "4" release, but this is the fourth wave of release, hence the name, Sonata 4).
    - [x] cache
        - [x] reconfigure Travis
        - [x] drop old versions of php & sf https://github.com/sonata-project/cache/pull/57
        - [x] drop php < 7.1 https://github.com/sonata-project/cache/pull/59
        - [x] `composer outdated` is empty https://github.com/sonata-project/cache/pull/60
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master https://github.com/sonata-project/cache/pull/64
    - [x] [google-authenticator](https://github.com/sonata-project/GoogleAuthenticator/projects/1)
        - [x] reconfigure Travis
        - [x] unstick StyleCI
        - [x] drop old versions of php & sf https://github.com/sonata-project/GoogleAuthenticator/pull/40
        - [x] drop php < 7.0 https://github.com/sonata-project/GoogleAuthenticator/pull/45
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master https://github.com/sonata-project/GoogleAuthenticator/pull/50
    - [x] easy-extends bundle
        - [x] unstick StyleCI
        - [x] drop old versions of php & sf  https://github.com/sonata-project/SonataEasyExtendsBundle/pull/103
        - [x] drop php < 7.1
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [x] exporter
        - [x] reconfigure Travis
        - [x] `composer outdated` is (almost) empty
        - [x] drop php < 7.1
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [x] doctrine-extensions
        - [x] reconfigure Travis
        - [x] drop old versions of php
        - [x] drop old versions of sf https://github.com/sonata-project/sonata-doctrine-extensions/pull/39
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [x] datagrid bundle
        - [x] reconfigure Travis
        - [x] drop old versions of php & sf  https://github.com/sonata-project/SonataDatagridBundle/pull/51
        - [x] drop php < 7.1 https://github.com/sonata-project/SonataDatagridBundle/pull/77
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
/pull/122
        - [x] drop php < 7.1
        - [x] `composer outdated` is empty https://github.com/sonata-project/SonataCacheBundle/pull/125
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master https://github.com/sonata-project/SonataCacheBundle/pull/160
    - [x] formatter bundle
        - [x] reconfigure Travis
        - [x] drop old versions of php & sf https://github.com/sonata-project/SonataFormatterBundle/pull/221
        - [x] drop php < 7.1
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [ ] Persistence bundles
        - [x] doctrine orm admin bundle
            - [x] drop old versions of php & sf
            - [x] `composer outdated` is empty https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/661
            - [x] remove `Extension::addClassesToCompile` if present
            - [x] remove most pipes from `composer.json` on master
        - [ ] doctrine phpcr admin bundle
            - [ ] drop old versions of php
            - [x] drop old versions of sf https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/411
            - [ ] `composer outdated` is empty
            - [ ] remove `Extension::addClassesToCompile` if present
            - [ ] remove most pipes from `composer.json` on master
        - [x] doctrine mongodb admin bundle
            - [x] drop old versions of sf https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/201
            - [x] `composer outdated` is empty
            - [x] remove `Extension::addClassesToCompile` if present
            - [x] remove most pipes from `composer.json` on master
        - [ ] propel bundle
            - [ ] `composer outdated` is empty
            - [ ] remove `Extension::addClassesToCompile` if present
            - [ ] remove most pipes from `composer.json` on master
    - [ ] seo bundle (admin depends on it)
        - [x] reconfigure Travis
        - [ ] drop old versions of php & sf
        - [ ] `composer outdated` is empty
        - [ ] remove `Extension::addClassesToCompile` if present
        - [ ] remove most pipes from `composer.json` on master
    - [x] block bundle (admin depends on it)
        - [x] reconfigure Travis
        - [x] drop old versions of php
        - [x] drop old versions of sf https://github.com/sonata-project/SonataBlockBundle/pull/352
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [x] intl bundle (admin depends on it) 
        - [x] drop old versions of php
        - [x] drop old versions of sf https://github.com/sonata-project/SonataBlockBundle/pull/352
        - [x] `composer outdated` is empty https://github.com/sonata-project/SonataIntlBundle/pull/150
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [ ] classification bundle (3 dependent bundles)
    - [x] user bundle (news depends on it)
        - [x] reconfigure Travis
        - [x] drop old versions of php & sf
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [ ] media bundle https://github.com/sonata-project/SonataMediaBundle/pull/1165
    - [x] admin bundle
        - [x] move common template to admin bundle: https://github.com/sonata-project/SonataAdminBundle/issues/2511
        - [x] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [x] remove most pipes from `composer.json` on master
    - [ ] admin search bundle
        - [ ] remove `Extension::addClassesToCompile` if present
        - [ ] remove most pipes from `composer.json` on master
    - [ ] notification bundle
        - [x] reconfigure Travis
        - [x] unstick StyleCI
        - [x] drop old versions of php & sf https://github.com/sonata-project/SonataNotificationBundle/pull/219
        - [x] drop php < 7.1
        - [ ] `composer outdated` is empty
        - [x] remove `Extension::addClassesToCompile` if present
        - [ ] remove most pipes from `composer.json` on master
- [ ] release dependent, root libraries
    - [ ] news bundle
        - [ ] `composer outdated` is empty
        - [ ] remove `Extension::addClassesToCompile` if present
        - [ ] remove most pipes from `composer.json` on master
    - [ ] page bundle
        - [ ] `composer outdated` is empty
        - [ ] remove `Extension::addClassesToCompile` if present
        - [ ] remove most pipes from `composer.json` on master
- [ ] drop old bundles
    - [x] core bundle
    - [ ] cache bundle

Here is a deps graph generated with `clue/graph-composer`
![deps](https://cloud.githubusercontent.com/assets/657779/20640254/2690bf50-b3d9-11e6-8de4-7c9fe53535f3.png)

Here is the same graph, with sonata-deps only (I deleted things manually with inkscape)
![deps svg](https://cloud.githubusercontent.com/assets/657779/20640408/561b8472-b3dd-11e6-9234-75bcd3a00e42.png)

For each library, we should : 
- reconfigure Travis on the master branch via dev-kit
- merge the stable branch in master one last time
- drop old versions of php
- drop old versions of symfony
- optionally drop old versions of dependencies
- cleanup `NEXT_MAJOR:` and `deprecated` things
- create a `$nextMajor.x` from master
- alias master to `$nextMajor + 1`
- for non-leaf libraries, explain the 3-branch system in CONTRIBUTING.md

About libraries, I think maybe we should support only one major version of a given library, and give  `doctrine/orm` a special treatment, maybe by supporting only the two last minor releases.
Thoughts?

**Comment by Soullivaneuh** [comment]
> We can revert to a 2 branch system after all dependent bundles have a new major release

No, the goal is exactly to keep a three branch system. :-)

Please see https://github.com/sonata-project/dev-kit/issues/153.

**Comment by greg0ire** [comment]
> No, the goal is exactly to keep a three branch system. :-)

Fine by me :)

**Comment by greg0ire** [comment]
> About libraries, I think maybe we should support only one major version of a given library, and give doctrine/orm a special treatment, maybe by supporting only the two last minor releases.

@sonata-project/contributors , can you give me your feeling about this ? It feels lonely here!

In more detail, I think the ideal plan would be

given dependency x : 
    - make sure we support the latest major version, if we don't, add support for it in the stable branch
    - in the master branch, drop support for all major versions that are not the latest

**Comment by core23** [comment]
Good work @greg0ire ! 

Before releasing the next major release of the admin bundle, there are still some stuff to do to have a clean new admin solution: https://github.com/sonata-project/SonataAdminBundle/milestone/6 IMHO it's the perfect time to remove some old edges, e.g. the overcomplicated `AbstractAdmin` class.

For the branch system: What about supporting the oldest version (version 3) with security patches for just one year when releasing the next major release (version 4). This would leave a clear sign to the people who are using old (outdated) software and would concentrate our power to the evoltion of our software.

**Comment by greg0ire** [comment]
> What about supporting the oldest version (version 3) with security patches for just one year when releasing the next major release (version 4). This would leave a clear sign to the people who are using old (outdated) software and would concentrate our power to the evolution of our software.

I think it's the plan :)

What do you think about the support plan I proposed for dependencies other than Sonata or Symfony?

**Comment by greg0ire** [comment]
For instance, for SonataMediaBundle, that would mean dropping support for FosRestBundle 1, jms/serializer 0, and gauffrette 0.1.
![what say you](https://m.popkey.co/f7a153/K6RMp.gif)

**Comment by core23** [comment]
We should also all `Extension::addClassesToCompile` for the next majors, because this part is only needed for < PHP 7. 

Refs https://github.com/symfony/symfony/pull/20735

**Comment by greg0ire** [comment]
You a word

**Comment by greg0ire** [comment]
I updated the list @core23

**Comment by core23** [comment]
What about PHP 7 type declarations? We've completly dropped PHP 5 support, so we could use the new type hinting stuff for every method.

**Comment by greg0ire** [comment]
Would it be a BC break though?

**Comment by core23** [comment]
Yes https://3v4l.org/iBbmb

**Comment by greg0ire** [comment]
You're getting it backwards again 😅 But anyway, [you're right](https://3v4l.org/SiL9X)

**Comment by greg0ire** [comment]
@sonata-project/contributors the big checklist is getting unwieldy. Maybe we could [create a "project" like this for every repo](https://github.com/sonata-project/cache/projects/)?

**Comment by core23** [comment]
Maybe use the milestones for this?

**Comment by greg0ire** [comment]
We would have every issue listed here in one "next major" milestone, so I don't think milestones would be useful here.

**Comment by greg0ire** [comment]
>  so we could use the new type hinting stuff for every method.

Started it on the cache library, it's an ordeal for us, and probably will be for our users. Also there's an RFC which could make this way more doable when we use php 7.2+

**Comment by core23** [comment]
For all bundles: we should drop PHP 7.0. Travis is already set up.

**Comment by ethernal** [comment]
Any news on progress and BTW will Symfony 4 be supported? Maybe skip the 3.0 or at least release one that supports 3.0 and then focus on 4.0 

What are the plans? If SF 3.0 is getting suport around or after SF 4.0 is released what are the chances of staying up to date?

**Comment by greg0ire** [comment]
I'm keeping the todo list up to date.

SF 4 support will probably be added as soon as sf 4 is out.

**Comment by ethernal** [comment]
That means FOS2 is also compatible with SF4? That's a relief ;-)

**Comment by greg0ire** [comment]
> That means FOS2 is also compatible with SF4? That's a relief ;-)

I'm not speaking for FOS, don't jump to conclusions.

**Comment by ethernal** [comment]
I thought so.. ^_^ I'm still stuck at SF 2.8

**Comment by greg0ire** [comment]
Well maybe start upgrading that :P

**Comment by JonathanBaudoin** [comment]
As I said [here](https://github.com/sonata-project/SonataUserBundle/issues/913), my company would like to help. But as often, some members do not realize the difficulty of apprehending a huge project like Sonata. Explanations pages (for PR for example) are not necessarily sufficient. But OK, if it's the only way to do it... It is too bad to discourage people who wish to help.

Were are going to use a specific commit.

**Comment by greg0ire** [comment]
Did you read the CONTRIBUTING.md ? We tried to explain at length how to contribute there. If you want to help, I think you might want to get doctrine-extensions closer to the goal. You can have a look at https://github.com/sonata-project/cache/projects/1 to see how it went for other projects.

> It is too bad to discourage people who wish to help.

Why are you saying this? Because you did not get the lengthy answer you hoped yet? Most of us are working right now, I'm sure you understand that.

**Comment by JonathanBaudoin** [comment]
We read it. But as I said, it's not easy to apprehend a huge project like Sonata. There are **a lot** of things, and we don't know all of them (_you_ know, the rest of the world doesn't). I didn't say that because I dit not get the answer I hoped... I did say that because we want to help but are not familiar with the Sonata workflow proccess, and it seems there are a lot of things to do with a lot of bundles. And, to resume, the @Soullivaneuh answer is: "do a PR". OK. Thanks. I was asking some human help to help Sonata. **That**'s too bad.

I don't know, a company offers to help, maybe it might have been interesting to talk with these people instead of closing the discussion by referring to a procedure.

Sorry for my expression, we can continue in french by mail if you want. ;)

**Comment by greg0ire** [comment]
You can also come on #sonata on [the symfony-devs slack](https://symfony.com/slack-invite). We might even start a french thread in there if you want.

**Comment by bmaziere** [comment]
@greg0ire very nice list ;) any chance to get it updated to help to move forward on the road to Sonata 4 🎉?

**Comment by greg0ire** [comment]
Thank you! Which part is outdated in your opinion?

**Comment by VincentLanglet** [comment]
Closing as we made some 4-rc releases and not following the checklist
