### ISSUE TITLE
Drop CoreBundle in Sonata 3 - process description

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#697]
CoreBundle use aliases in deprecated classes. This mean we can replace This class by new even in Sonata 3, becouse they equal and will be BC. For example:
`Sonata\CoreBundle\Validator\ErrorElement === Sonata\Form\Validator\ErrorElement`.
Other things like `FormHelper::registerFormMapping` can be optional - after checking is class exists.

This change will allow drop CoreBundle from dependencies and use:
- 0.x -extensions - step to drop CoreBundle, make working extensions instead
- 1.x -extensions - to work with Sonata 3 and Sonata 4 with CoreBundle conflict
    - drop serializer and StatusClassRenderInterFace type hints are require    
- 2.x -extensions - to work with Sonata 4 if we want drop all return types hints in 1.x

## TODO
- [x] __STEP 1__ - prepare to split
    - [x] prepare extensions 0.x
        - [x] [release stable form-extensions 0.1](https://github.com/sonata-project/form-extensions/pull/92)
        - [x] [release stable twig-extensions 0.1](https://github.com/sonata-project/twig-extensions/pull/80)
    - [x] prepare extensions 1.x
        - [x] [Downgrade to use in Sonata 3](https://github.com/sonata-project/form-extensions/pull/94)
        - [x] [Downgrade to use in Sonata 3](https://github.com/sonata-project/twig-extensions/pull/82)
    - [x] prepare CoreBundle
        - [x] https://github.com/sonata-project/SonataCoreBundle/pull/751
- [x] __STEP 2__ - split SonataCoreBundle
    - [x] https://github.com/sonata-project/SonataCoreBundle/pull/752
- [x] __STEP 3__ - drop SonataCoreBundle dependencies in:
    - [x] [sonata-project/admin-bundle](https://github.com/sonata-project/SonataAdminBundle/pull/6096)
    - [x] [sonata-project/block-bundle](https://github.com/sonata-project/SonataBlockBundle/pull/704)
    - [x] [sonata-project/classification-bundle](https://github.com/sonata-project/SonataClassificationBundle/pull/531)
    - [x] [sonata-project/comment-bundle](https://github.com/sonata-project/SonataCommentBundle/pull/185)
    - [x] [sonata-project/doctrine-orm-admin-bundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1048)
    - [x] [sonata-project/ecommerce](https://github.com/sonata-project/ecommerce/pull/672)
    - [x] [sonata-project/formatter-bundle](https://github.com/sonata-project/SonataFormatterBundle/pull/459)
    - [x] [sonata-project/media-bundle](https://github.com/sonata-project/SonataMediaBundle/pull/1744)
    - [x] [sonata-project/news-bundle](https://github.com/sonata-project/SonataNewsBundle/pull/595)
    - [x] [sonata-project/notification-bundle](https://github.com/sonata-project/SonataNotificationBundle/pull/440)
    - [x] [sonata-project/page-bundle](https://github.com/sonata-project/SonataPageBundle/pull/1156)
    - [x] [sonata-project/seo-bundle](https://github.com/sonata-project/SonataSeoBundle/pull/394)
    - [x] [sonata-project/timeline-bundle](https://github.com/sonata-project/SonataTimelineBundle/pull/255)
    - [x] [sonata-project/user-bundle ](https://github.com/sonata-project/SonataUserBundle/pull/1173)
    - [x] [SonataDashboardBundle](https://github.com/sonata-project/SonataDashboardBundle/pull/223)
- [ ]  __(OPTIONAL) Step 4__  Drop CoreBundle in less usages bundles
    - [ ] SonataDoctrinePhpcrAdminBundle
    - [x] [SonataDoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/375)
- [x]  __(FINAL) Step 5__  [Drop CoreBundle from sandbox](https://github.com/sonata-project/sandbox/pull/626)

**Comment by wbloszyk** [comment]
WDYT @core23 @phansys @VincentLanglet @greg0ire @contributors

1. Should we drop all return type hints in 1.x-extension or only required?
1. Should we move FormHelper to form-extensions?

**Comment by greg0ire** [comment]
> Should we drop all return type hints in 1.x-extension or only required?

We should only drop return type declarations that prevent the migration IMO

**Comment by greg0ire** [comment]
> Should we move FormHelper to form-extensions?

I don't know what it does or why it wasn't migrated in the first place, but given the name that would make sense I suppose.

**Comment by greg0ire** [comment]
Why are all the PRs above with a draft status?

**Comment by wbloszyk** [comment]
@greg0ire becouse form-extensions and twig-extensions 0.1 stable are require.

**Comment by wbloszyk** [comment]
@core23 @greg0ire @phansys @VincentLanglet @contributors

I __DONE__ this issue. 

You can reproduce sandbox by:
```
git clone https://github.com/wbloszyk/sandbox.git
git checkout drop_core_preview
// create env.local with database config
vendor/bin/phing
```

I need this change before open PRs. Can you do it:
1. https://github.com/sonata-project/SonataCoreBundle/pull/751 check and release as 3.19.2
1. Release stable extensions:
    - https://github.com/sonata-project/twig-extensions/pull/80
    - https://github.com/sonata-project/form-extensions/pull/92
1. https://github.com/sonata-project/SonataCoreBundle/pull/752 check and release as 3.20

**Comment by wbloszyk** [comment]
@sonata-project/contributors

Can you try check __STEP 1__  in this weekend?  I need this change in next week. I will be greatful.

**Comment by VincentLanglet** [comment]
> @contributors 
 
You're pinging a random guy, instead of @sonata-project/contributors

**Comment by wbloszyk** [comment]
Lets try @sonata-project/contributors

**Comment by wbloszyk** [comment]
@greg0ire 
STEP 1 is almost done. Can you release this change (5 releases)? For now you can release CoreBundle. This will allow prepare STEP 2.

**Comment by greg0ire** [comment]
All done :)

**Comment by wbloszyk** [comment]
Thanks :)

**Comment by wbloszyk** [comment]
Some bundles still need update dependencies. Anyway PRs are independent. Feel free to check it.

**Comment by wbloszyk** [comment]
Based on: https://github.com/sonata-project/twig-extensions/issues/86#issuecomment-639601703

I will drop `twig/twig-extension` in favor for `twig/extra-bundle` and replace `truncate` to `u.truncate`. I will add DeprecatedTextExtensionTest for `truncate` based on this `u.truncate` filter to keep BC too.

**Comment by jordisala1991** [comment]
I think that we only need to move the missing class.

**Comment by wbloszyk** [comment]
This will be enought. I think we can do something more. Anyway it is work for Monday. Weekend time start :).

**Comment by wbloszyk** [comment]
Probably drop CoreBundle in BlockBundle 3 is impossible. `jms/di-extra-bundle` do not allow upgrade it and also can not be drop without BC-break. 

I think we can add support for BlockBundle 4 instead.

**Comment by jordisala1991** [comment]
We are missing some bundles here like phpcr or mongodb also

**Comment by wbloszyk** [comment]
PageBundle functional test require SonataAdminBundle release. I will change to `Ready for review` after that.

**Comment by jordisala1991** [comment]
> Probably drop CoreBundle in BlockBundle 3 is impossible. jms/di-extra-bundle do not allow upgrade it and also can not be drop without BC-break.

https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/composer.json

This bundle is not even compatible with sf4, and it is on our require dev. @sonata-project/contributors can it be an acceptable bc break if we remove support for sf 3 on block 3 and that forces us to remove that bu dle from require dev?

The problem is the admin 3 cant fully remove corebundle if block 3 does not remove core bundle, because it is a dependency.

**Comment by VincentLanglet** [comment]
> @sonata-project/contributors can it be an acceptable bc break if we remove support for sf 3

Removing support for sf3 is not a BC-break.

**Comment by jordisala1991** [comment]
I know, but removing support for sf3 will force us to remove jms di-extra-bundle. That’s why I am asking.

**Comment by VincentLanglet** [comment]
> I know, but removing support for sf3 will force us to remove jms di-extra-bundle.

But since it's a dev requirement, it's not a BC-break either.

That's why I don't understand the following point

> @sonata-project/contributors can it be an acceptable bc break if ...

Both removing support for SF3 and removing jms are not BC-break

If it's mandatory, let's go with it then.

**Comment by wbloszyk** [comment]
Force user to drop CoreBundle and extensions 0.x in Sonata 3 is mandatory, even it must be done.

**Comment by wbloszyk** [comment]
In extensions 1.x are conflicts:
```json
    "conflict": {
        "sonata-project/core-bundle": ">=3.13"
    },
```
In CoreBundle 3.20:
```json
    "require": {
        "sonata-project/form-extensions": "^0.1.1",
        "sonata-project/twig-extensions": "^0.1.1"
    }
```
Composer install CoreBundle 3.12 and extensions 1.x but should CoreBundle 3.20 and extensions 0.x.

I think we have to update extensions 1.x and set conflict to any CoreBundle version.

Remove process should look like:
- update CoreBundle to 3.20
- remove deprecations
- remove CoreBundle
- upgrade extensions to 1.x

CoreBundle with extensions 1.x should not be allowed. 

@sonata-project/contributors WDYT?

**Comment by greg0ire** [comment]
It sounds like a good upgrade path :)

**Comment by wbloszyk** [comment]
@sonata-project/contributors
I check amlost all Sonata 3 project. In some of it Symfony3 and php 7.1 is still support. I think we should drop it. WDYT?

**Comment by core23** [comment]
> @sonata-project/contributors

This does not work for you, unless you are part of the contributors.

> In some of it Symfony3 and php 7.1 is still support. I think we should drop it. WDYT?

We should update our BC promise in that case: https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md#dependency-changes

**Comment by wbloszyk** [comment]
@core23 
if I understood correctly php7.2 and Symfony 4.3 is minimum version which must be support.

**Comment by jordisala1991** [comment]
> We should update our BC promise in that case: https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md#dependency-changes

Drop support for php 7.1 is allowed by the guidelines (it is not on the orange zone), and the sf 3 drop is allowed too (we give support for one lts already).

**Comment by wbloszyk** [comment]
@core23 @greg0ire @phansys @VincentLanglet @jordisala1991 

I update test branch in sandbox. You can reproduce it by:
```
git clone https://github.com/wbloszyk/sandbox.git
git checkout drop_core_preview
// create env.local with database config
vendor/bin/phing
```

**Comment by wbloszyk** [comment]
@greg0ire Some release description for you.

Release process will be little big for it and contains drop corebundle and also truncate (twig/twig-extensions) in favor for `u` filter. Also there is some dependencies in tests which should be keep.

1. AdminBundle
    - [ ] https://github.com/sonata-project/SonataAdminBundle/pull/6132
    - [ ] release
2. Change truncate to `u` filter:
    - [ ] NewsBundle
    - [ ]  Ecommerce
    - [ ]  MediaBundle
    - [ ] PageBundle
3. Releases other bundles
4. Merge to master branch

**Comment by wbloszyk** [comment]
@greg0ire Can you release FormatterBundle?

**Comment by wbloszyk** [comment]
@greg0ire Can you release:
- [ ] NotificationBundle
- [ ] DoctrineORMAdminBundle
- [ ] SeoBundle

This should fix functional test in PageBundle.

**Comment by greg0ire** [comment]
@wbloszyk please ask on the #releases channel on slack next time, it will be faster, I can't keep up with my github notifications :P

**Comment by wbloszyk** [comment]
@greg0ire I will be remember about it. 

BTW. This issue will be done in this month (in June). :tada:

**Comment by greg0ire** [comment]
Thanks a lot for all this work! You rock!

**Comment by jordisala1991** [comment]
This one is almost done, we are still missing the other persistence bundles, sandbox and remove it from dev kit, because most of the projects have special builds with corebundle

**Comment by wbloszyk** [comment]
I have sandbox for it but some bundles must be release before it. CoreBundle id now optional in sonata 3. I think we can keep this dev-kit config and must delete in sonata 4.

**Comment by wbloszyk** [comment]
Releases free from CoreBundle:
3.69 - admin-bundle 
3.20 - block-bundle
3.12 - classification-bundle
3.2  - comment-bundle
3.19 - doctrine-orm-admin-bundle
3.3  - commerce
4.2  - formatter-bundle
3.25 - media-bundle
3.13 - news-bundle
3.8  - notification-bundle
3.18 - page-bundle
2.11 - seo-bundle
3.6  - timeline-bundle
4.6  - user-bundle
0.4  - dashboard-bundle

**Comment by wbloszyk** [comment]
What with `SonataDoctrinePhpcrAdminBundle`? After drop `CoreBundle` and bump dev-require `"jms/serializer-bundle": "^3.3", we little in conflict.

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/dev-kit/issues/659

IMHO there is no active support on this bundle. Recently when we added a new feature, it was always on the two others storage bundle, with no backport on the Phpcr bundle since no maintainers are using it.

**Comment by wbloszyk** [comment]
I think we can close this issue. Feel free to open it if `SonataDoctrinePhpcrAdminBundle` will be support.
