### ISSUE TITLE
Add support to BlockBundle v4

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#785]
## TODO: 
- [x] sandbox
    - `AccountBlockService` extends `AbstractAdminBlockService`
    - `NewsletterBlockService` extends `BaseBlockService`
- [ ] ecommerce
    - Basket
        - `BasketBlockService` extends `AbstractAdminBlockService`
    - Customer
        - final class `ProfileMenuBlockService` extends `MenuBlockService`
        - `RecentCustomersBlockService` extends `AbstractAdminBlockService`
    - Order
        - `RecentOrdersBlockService` extends `BaseBlockService`
    - Product
        - `CatalogBreadcrumbBlockService` extends `BaseBreadcrumbMenuBlockService`
        - `CategoriesMenuBlockService` extends `MenuBlockService`
        - `FiltersMenuBlockService` extends `MenuBlockService`
        - `RecentProductsBlockService` extends `BaseBlockService`
        - `SimilarProductsBlockService` extends `BaseBlockService`
        - `VariationsFormBlockService` extends `BaseBlockService`
- [x] [SonataAdminBundle](https://github.com/sonata-project/SonataAdminBundle/pull/6212)
    - `AdminListBlockService` extends `AbstractBlockService`
    - `AdminSearchBlockService` extends `AbstractBlockService`
    - `AdminStatsBlockService` extends `AbstractBlockService`
- [x] SonataClassificationBundle
    - `AbstractCategoriesBlockService` extends `AbstractClassificationBlockService`
    - `AbstractClassificationBlockService` extends `AbstractAdminBlockService`
    - `AbstractCollectionsBlockService` extends `AbstractClassificationBlockService`
    - `AbstractTagsBlockService` extends `AbstractClassificationBlockService`
- [ ] SonataCommentBundle
    - `CommentThreadAsyncBlockService` extends `BaseBlockService`
- [ ] SonataDashboardBundle
    - `ContainerBlockService` extends `BaseContainerBlockService`
- [x] [SonataDoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1023)
    - `AuditBlockService` extends `AbstractBlockService`
- [ ] SonataDoctrinePhpcrAdminBundle
    - `TreeBlockService` extends `AbstractBlockService`
- [x] SonataFormatterBundle
    - `FormatterBlockService` extends `AbstractAdminBlockService`
- [x] SonataMediaBundle
    - Breadrumb
        - `BaseGalleryBreadcrumbBlockService` extends `BaseBreadcrumbMenuBlockService`
        - `GalleryIndexBreadcrumbBlockService` extends `BaseGalleryBreadcrumbBlockService`
        - `GalleryViewBreadcrumbBlockService` extends `BaseGalleryBreadcrumbBlockService`
        - `MediaViewBreadcrumbBlockService` extends `BaseGalleryBreadcrumbBlockService`
    - `FeatureMediaBlockService` extends `MediaBlockService`
    - `GalleryBlockService` extends `AbstractBlockService`
    - `GalleryListBlockService` extends `AbstractBlockService`
    - `MediaBlockService` extends `AbstractBlockService`
- [ ] SonataNewsBundle
    - Breadcrumb
        - `BaseNewsBreadcrumbBlockService` extends `BaseBreadcrumbMenuBlockService`
        - `NewsArchiveBreadcrumbBlockService` extends `BaseNewsBreadcrumbBlockService`
        - `NewsPostBreadcrumbBlockService` extends `BaseNewsBreadcrumbBlockService`
    - `RecentCommentsBlockService` extends `AbstractAdminBlockService`
    - `RecentPostsBlockService` extends `AbstractAdminBlockService`
- [ ] SonataPageBundle
    - `BlockContextManager` extends `BaseBlockContextManager`
    - `BreadcrumbBlockService` extends `BaseBreadcrumbMenuBlockService`
    - `ChildrenPagesBlockService` extends `AbstractAdminBlockService`
    - `ContainerBlockService` extends `BaseContainerBlockService`
    - `PageListBlockService` extends `AbstractAdminBlockService`
    - `SharedBlockBlockService` extends `AbstractAdminBlockService`
- [x] SonataSeoBundle
    - Breadcrumb
        - `BaseBreadcrumbMenuBlockService` extends `MenuBlockService`
        - `HomepageBreadcrumbBlockService` extends `BaseBreadcrumbMenuBlockService`
    - Social
        - `BaseFacebookSocialPluginsBlockService` extends `AbstractAdminBlockService`
        - `BaseTwitterButtonBlockService` extends `AbstractAdminBlockService`
        - `EmailShareButtonBlockService` extends `AbstractAdminBlockService`
        - `FacebookLikeBoxBlockService` extends `BaseFacebookSocialPluginsBlockService`
        - `FacebookLikeButtonBlockService` extends `BaseFacebookSocialPluginsBlockService`
        - `FacebookSendButtonBlockService` extends `BaseFacebookSocialPluginsBlockService`
        - `FacebookShareButtonBlockService` extends `BaseFacebookSocialPluginsBlockService`
        - `PinterestPinButtonBlockService` extends `AbstractAdminBlockService`
        - `TwitterEmbedTweetBlockService` extends `BaseTwitterButtonBlockService`
        - `TwitterFollowButtonBlockService` extends `BaseTwitterButtonBlockService`
        - `TwitterHashtagButtonBlockService` extends `BaseTwitterButtonBlockService`
        - `TwitterMentionButtonBlockService` extends `BaseTwitterButtonBlockService`
        - `TwitterShareButtonBlockService` extends `BaseTwitterButtonBlockService`
- [ ] SonataTimelineBundle
    - `TimelineBlock` extends `AbstractAdminBlockService`
- [x] [SonataTranslationBundle](https://github.com/sonata-project/SonataTranslationBundle/pull/375)
    - `LocaleSwitcherBlockService` extends `AbstractBlockService`

**Comment by wbloszyk** [comment]
IMHO, Support for BlockBundle v4 should not be add in Sonata 3, It can be done in easy way when block will be final. Also in Sonata 4 support for BlockBundle v3 can be keep. 

We should consider add support for BlockBuindle v4 (useful for standalone Admin):
- SonataAdminBundle
- SonataDoctrineORMAdminBundle
- SonataDoctrinePhpcrAdminBundle
- SonataTranslationBundle

WDYT? Can you ping contributors too? @jordisala1991

**Comment by jordisala1991** [comment]
There are some bundles that could be hard to upgrade, but some others are easy and should be upgraded

**Comment by VincentLanglet** [comment]
Now we deprecated multiple bundles, the only non-deprecated bundle without the support of BlockBundle v4 is the page bundle.
