### ISSUE TITLE
Bump sonata-project/datagrid-bundle to version ^3.0

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/dev-kit#993]
After [bump sonata-project/datagrid-bundle to version ^3.0 in NotificationBundle](https://github.com/sonata-project/SonataNotificationBundle/pull/471) I can not install it on sandbox. We should revert it or update other bundles. IMO we need upgrade them to support
```
composer prohibits sonata-project/datagrid-bundle 3.0
sonata-project/sandbox              dev-4.0_admin_update  requires  sonata-project/datagrid-bundle (^2.4)    
sonata-project/ecommerce            3.3.0                 requires  sonata-project/datagrid-bundle (^2.5)    
sonata-project/news-bundle          3.14.0                requires  sonata-project/datagrid-bundle (^2.3.1)  
sonata-project/notification-bundle  3.9.0                 requires  sonata-project/datagrid-bundle (^2.5)    
sonata-project/page-bundle          3.19.0                requires  sonata-project/datagrid-bundle (^2.5)    
sonata-project/user-bundle          4.8.0                 requires  sonata-project/datagrid-bundle (^2.4.0)  
```

## TODO
- [x] [sonata-project/notification-bundle](https://github.com/sonata-project/SonataNotificationBundle/pull/471)
- [x] [add support to v3 in sonata-project/news-bundle](https://github.com/sonata-project/SonataNewsBundle/pull/639)   
- [ ] drop support for v2 in sonata-project/news-bundle   
- [x] [add support to v3 in sonata-project/page-bundle](https://github.com/sonata-project/SonataPageBundle/pull/1202)
- [ ] drop support for v2 in sonata-project/page-bundle
- [x] [sonata-project/user-bundle](https://github.com/sonata-project/SonataUserBundle/pull/1230)
- [x] [sonata-project/ecommerce](https://github.com/sonata-project/ecommerce/pull/714)

## and after releases:
- [x] sonata-project/sandbox

@core23 Can you do it?

**Comment by OskarStark** [comment]
dump or bump? 😃

**Comment by wbloszyk** [comment]
`sonata-project/datagrid-bundle` > 3.0 work on sandbox now.
